<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<title>JobEntry - Job Portal Website Template</title>';
echo '<meta content="width=device-width, initial-scale=1.0" name="viewport">';
echo '<meta content="" name="keywords">';
echo '<meta content="" name="description">';
echo '';
echo '<!-- Favicon -->';
echo '<link href="img/favicon.ico" rel="icon">';
echo '';
echo '<!-- Google Web Fonts -->';
echo '<link rel="preconnect" href="https://fonts.googleapis.com">';
echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
echo '<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">';
echo '';
echo '<!-- Icon Font Stylesheet -->';
echo '<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">';
echo '';
echo '<!-- Libraries Stylesheet -->';
echo '<link href="lib/animate/animate.min.css" rel="stylesheet">';
echo '<link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">';
echo '';
echo '<!-- Customized Bootstrap Stylesheet -->';
echo '<link href="css/bootstrap.min.css" rel="stylesheet">';
echo '';
echo '<!-- Template Stylesheet -->';
echo '<link href="css/style.css" rel="stylesheet">';
echo '</head>';
echo '';
echo '<body>';
echo '<div class="container-xxl bg-white p-0">';
echo '<!-- Spinner Start -->';
echo '<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">';
echo '<div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">';
echo '<span class="sr-only">Loading...</span>';
echo '</div>';
echo '</div>';
echo '<!-- Spinner End -->';
echo '';
echo '';
echo '<!-- Navbar Start -->';
echo '<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">';
echo '<a href="index.php" class="navbar-brand d-flex align-items-center text-center py-0 px-4 px-lg-5">';
echo '<h1 class="m-0 text-primary">JobEntry</h1>';
echo '</a>';
echo '<button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse" id="navbarCollapse">';
echo '<div class="navbar-nav ms-auto p-4 p-lg-0">';
echo '<a href="index.php" class="nav-item nav-link">Home</a>';
echo '<a href="about.php" class="nav-item nav-link">About</a>';
echo '<div class="nav-item dropdown">';
echo '<a href="#" class="nav-link dropdown-toggle active" data-bs-toggle="dropdown">Jobs</a>';
echo '<div class="dropdown-menu rounded-0 m-0">';
echo '<a href="job-list.php" class="dropdown-item">Job List</a>';
echo '<a href="job-detail.php" class="dropdown-item active">Job Detail</a>';
echo '</div>';
echo '</div>';
echo '<div class="nav-item dropdown">';
echo '<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>';
echo '<div class="dropdown-menu rounded-0 m-0">';
echo '<a href="category.php" class="dropdown-item">Job Category</a>';
echo '<a href="testimonial.php" class="dropdown-item">Testimonial</a>';
echo '<a href="404.php" class="dropdown-item">404</a>';
echo '</div>';
echo '</div>';
echo '<a href="contact.php" class="nav-item nav-link">Contact</a>';
echo '</div>';
echo '<a href="" class="btn btn-primary rounded-0 py-4 px-lg-5 d-none d-lg-block">Post A Job<i class="fa fa-arrow-right ms-3"></i></a>';
echo '</div>';
echo '</nav>';
echo '<!-- Navbar End -->';
echo '';
echo '';
echo '<!-- Header End -->';
echo '<div class="container-xxl py-5 bg-dark page-header mb-5">';
echo '<div class="container my-5 pt-5 pb-4">';
echo '<h1 class="display-3 text-white mb-3 animated slideInDown">Job Detail</h1>';
echo '<nav aria-label="breadcrumb">';
echo '<ol class="breadcrumb text-uppercase">';
echo '<li class="breadcrumb-item"><a href="#">Home</a></li>';
echo '<li class="breadcrumb-item"><a href="#">Pages</a></li>';
echo '<li class="breadcrumb-item text-white active" aria-current="page">Job Detail</li>';
echo '</ol>';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '<!-- Header End -->';
echo '';
echo '';
echo '<!-- Job Detail Start -->';
echo '<div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">';
echo '<div class="container">';
echo '<div class="row gy-5 gx-4">';
echo '<div class="col-lg-8">';
echo '<div class="d-flex align-items-center mb-5">';
echo '<img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-2.jpg" alt="" style="width: 80px; height: 80px;">';
echo '<div class="text-start ps-4">';
echo '<h3 class="mb-3">Marketing Manager</h3>';
echo '<span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>';
echo '<span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>';
echo '<span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="mb-5">';
echo '<h4 class="mb-3">Job description</h4>';
echo '<p>Dolor justo tempor duo ipsum accusam rebum gubergren erat. Elitr stet dolor vero clita labore gubergren. Kasd sed ipsum elitr clita rebum ut sea diam tempor. Sadipscing nonumy vero labore invidunt dolor sed, eirmod dolore amet aliquyam consetetur lorem, amet elitr clita et sed consetetur dolore accusam. Vero kasd nonumy justo rebum stet. Ipsum amet sed lorem sea magna. Rebum vero dolores dolores elitr vero dolores magna, stet sea sadipscing stet et. Est voluptua et sanctus at sanctus erat vero sed sed, amet duo no diam clita rebum duo, accusam tempor takimata clita stet nonumy rebum est invidunt stet, dolor.</p>';
echo '<h4 class="mb-3">Responsibility</h4>';
echo '<p>Magna et elitr diam sed lorem. Diam diam stet erat no est est. Accusam sed lorem stet voluptua sit sit at stet consetetur, takimata at diam kasd gubergren elitr dolor</p>';
echo '<ul class="list-unstyled">';
echo '<li><i class="fa fa-angle-right text-primary me-2"></i>Dolor justo tempor duo ipsum accusam</li>';
echo '<li><i class="fa fa-angle-right text-primary me-2"></i>Elitr stet dolor vero clita labore gubergren</li>';
echo '<li><i class="fa fa-angle-right text-primary me-2"></i>Rebum vero dolores dolores elitr</li>';
echo '<li><i class="fa fa-angle-right text-primary me-2"></i>Est voluptua et sanctus at sanctus erat</li>';
echo '<li><i class="fa fa-angle-right text-primary me-2"></i>Diam diam stet erat no est est</li>';
echo '</ul>';
echo '<h4 class="mb-3">Qualifications</h4>';
echo '<p>Magna et elitr diam sed lorem. Diam diam stet erat no est est. Accusam sed lorem stet voluptua sit sit at stet consetetur, takimata at diam kasd gubergren elitr dolor</p>';
echo '<ul class="list-unstyled">';
echo '<li><i class="fa fa-angle-right text-primary me-2"></i>Dolor justo tempor duo ipsum accusam</li>';
echo '<li><i class="fa fa-angle-right text-primary me-2"></i>Elitr stet dolor vero clita labore gubergren</li>';
echo '<li><i class="fa fa-angle-right text-primary me-2"></i>Rebum vero dolores dolores elitr</li>';
echo '<li><i class="fa fa-angle-right text-primary me-2"></i>Est voluptua et sanctus at sanctus erat</li>';
echo '<li><i class="fa fa-angle-right text-primary me-2"></i>Diam diam stet erat no est est</li>';
echo '</ul>';
echo '</div>';
echo '';
echo '<div class="">';
echo '<h4 class="mb-4">Apply For The Job</h4>';
echo '<form>';
echo '<div class="row g-3">';
echo '<div class="col-12 col-sm-6">';
echo '<input type="text" class="form-control" placeholder="Your Name">';
echo '</div>';
echo '<div class="col-12 col-sm-6">';
echo '<input type="email" class="form-control" placeholder="Your Email">';
echo '</div>';
echo '<div class="col-12 col-sm-6">';
echo '<input type="text" class="form-control" placeholder="Portfolio Website">';
echo '</div>';
echo '<div class="col-12 col-sm-6">';
echo '<input type="file" class="form-control bg-white">';
echo '</div>';
echo '<div class="col-12">';
echo '<textarea class="form-control" rows="5" placeholder="Coverletter"></textarea>';
echo '</div>';
echo '<div class="col-12">';
echo '<button class="btn btn-primary w-100" type="submit">Apply Now</button>';
echo '</div>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-4">';
echo '<div class="bg-light rounded p-5 mb-4 wow slideInUp" data-wow-delay="0.1s">';
echo '<h4 class="mb-4">Job Summery</h4>';
echo '<p><i class="fa fa-angle-right text-primary me-2"></i>Published On: 01 Jan, 2045</p>';
echo '<p><i class="fa fa-angle-right text-primary me-2"></i>Vacancy: 123 Position</p>';
echo '<p><i class="fa fa-angle-right text-primary me-2"></i>Job Nature: Full Time</p>';
echo '<p><i class="fa fa-angle-right text-primary me-2"></i>Salary: $123 - $456</p>';
echo '<p><i class="fa fa-angle-right text-primary me-2"></i>Location: New York, USA</p>';
echo '<p class="m-0"><i class="fa fa-angle-right text-primary me-2"></i>Date Line: 01 Jan, 2045</p>';
echo '</div>';
echo '<div class="bg-light rounded p-5 wow slideInUp" data-wow-delay="0.1s">';
echo '<h4 class="mb-4">Company Detail</h4>';
echo '<p class="m-0">Ipsum dolor ipsum accusam stet et et diam dolores, sed rebum sadipscing elitr vero dolores. Lorem dolore elitr justo et no gubergren sadipscing, ipsum et takimata aliquyam et rebum est ipsum lorem diam. Et lorem magna eirmod est et et sanctus et, kasd clita labore.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Job Detail End -->';
echo '';
echo '';
echo '<!-- Footer Start -->';
echo '<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">';
echo '<div class="container py-5">';
echo '<div class="row g-5">';
echo '<div class="col-lg-3 col-md-6">';
echo '<h5 class="text-white mb-4">Company</h5>';
echo '<a class="btn btn-link text-white-50" href="">About Us</a>';
echo '<a class="btn btn-link text-white-50" href="">Contact Us</a>';
echo '<a class="btn btn-link text-white-50" href="">Our Services</a>';
echo '<a class="btn btn-link text-white-50" href="">Privacy Policy</a>';
echo '<a class="btn btn-link text-white-50" href="">Terms & Condition</a>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<h5 class="text-white mb-4">Quick Links</h5>';
echo '<a class="btn btn-link text-white-50" href="">About Us</a>';
echo '<a class="btn btn-link text-white-50" href="">Contact Us</a>';
echo '<a class="btn btn-link text-white-50" href="">Our Services</a>';
echo '<a class="btn btn-link text-white-50" href="">Privacy Policy</a>';
echo '<a class="btn btn-link text-white-50" href="">Terms & Condition</a>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<h5 class="text-white mb-4">Contact</h5>';
echo '<p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>';
echo '<p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>';
echo '<p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>';
echo '<div class="d-flex pt-2">';
echo '<a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>';
echo '<a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>';
echo '<a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>';
echo '<a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<h5 class="text-white mb-4">Newsletter</h5>';
echo '<p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>';
echo '<div class="position-relative mx-auto" style="max-width: 400px;">';
echo '<input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">';
echo '<button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="copyright">';
echo '<div class="row">';
echo '<div class="col-md-6 text-center text-md-start mb-3 mb-md-0">';
echo '&copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.';
echo '';
echo '<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you had like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->';
echo 'Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>';
echo '</div>';
echo '<div class="col-md-6 text-center text-md-end">';
echo '<div class="footer-menu">';
echo '<a href="">Home</a>';
echo '<a href="">Cookies</a>';
echo '<a href="">Help</a>';
echo '<a href="">FQAs</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Footer End -->';
echo '';
echo '';
echo '<!-- Back to Top -->';
echo '<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>';
echo '</div>';
echo '';
echo '<!-- JavaScript Libraries -->';
echo '<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>';
echo '<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>';
echo '<script src="lib/wow/wow.min.js"></script>';
echo '<script src="lib/easing/easing.min.js"></script>';
echo '<script src="lib/waypoints/waypoints.min.js"></script>';
echo '<script src="lib/owlcarousel/owl.carousel.min.js"></script>';
echo '';
echo '<!-- Template Javascript -->';
echo '<script src="js/main.js"></script>';
echo '</body>';
echo '';
echo '</html>';
?>