<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<title>JobEntry - Job Portal Website Template</title>';
echo '<meta content="width=device-width, initial-scale=1.0" name="viewport">';
echo '<meta content="" name="keywords">';
echo '<meta content="" name="description">';
echo '';
echo '<!-- Favicon -->';
echo '<link href="img/favicon.ico" rel="icon">';
echo '';
echo '<!-- Google Web Fonts -->';
echo '<link rel="preconnect" href="https://fonts.googleapis.com">';
echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
echo '<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">';
echo '';
echo '<!-- Icon Font Stylesheet -->';
echo '<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">';
echo '';
echo '<!-- Libraries Stylesheet -->';
echo '<link href="lib/animate/animate.min.css" rel="stylesheet">';
echo '<link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">';
echo '';
echo '<!-- Customized Bootstrap Stylesheet -->';
echo '<link href="css/bootstrap.min.css" rel="stylesheet">';
echo '';
echo '<!-- Template Stylesheet -->';
echo '<link href="css/style.css" rel="stylesheet">';
echo '</head>';
echo '';
echo '<body>';
echo '<div class="container-xxl bg-white p-0">';
echo '<!-- Spinner Start -->';
echo '<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">';
echo '<div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">';
echo '<span class="sr-only">Loading...</span>';
echo '</div>';
echo '</div>';
echo '<!-- Spinner End -->';
echo '';
echo '';
echo '<!-- Navbar Start -->';
echo '<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">';
echo '<a href="index.php" class="navbar-brand d-flex align-items-center text-center py-0 px-4 px-lg-5">';
echo '<h1 class="m-0 text-primary">JobEntry</h1>';
echo '</a>';
echo '<button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse" id="navbarCollapse">';
echo '<div class="navbar-nav ms-auto p-4 p-lg-0">';
echo '<a href="index.php" class="nav-item nav-link">Home</a>';
echo '<a href="about.php" class="nav-item nav-link">About</a>';
echo '<div class="nav-item dropdown">';
echo '<a href="#" class="nav-link dropdown-toggle active" data-bs-toggle="dropdown">Jobs</a>';
echo '<div class="dropdown-menu rounded-0 m-0">';
echo '<a href="job-list.php" class="dropdown-item active">Job List</a>';
echo '<a href="job-detail.php" class="dropdown-item">Job Detail</a>';
echo '</div>';
echo '</div>';
echo '<div class="nav-item dropdown">';
echo '<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>';
echo '<div class="dropdown-menu rounded-0 m-0">';
echo '<a href="category.php" class="dropdown-item">Job Category</a>';
echo '<a href="testimonial.php" class="dropdown-item">Testimonial</a>';
echo '<a href="404.php" class="dropdown-item">404</a>';
echo '</div>';
echo '</div>';
echo '<a href="contact.php" class="nav-item nav-link">Contact</a>';
echo '</div>';
echo '<a href="" class="btn btn-primary rounded-0 py-4 px-lg-5 d-none d-lg-block">Post A Job<i class="fa fa-arrow-right ms-3"></i></a>';
echo '</div>';
echo '</nav>';
echo '<!-- Navbar End -->';
echo '';
echo '';
echo '<!-- Header End -->';
echo '<div class="container-xxl py-5 bg-dark page-header mb-5">';
echo '<div class="container my-5 pt-5 pb-4">';
echo '<h1 class="display-3 text-white mb-3 animated slideInDown">Job List</h1>';
echo '<nav aria-label="breadcrumb">';
echo '<ol class="breadcrumb text-uppercase">';
echo '<li class="breadcrumb-item"><a href="#">Home</a></li>';
echo '<li class="breadcrumb-item"><a href="#">Pages</a></li>';
echo '<li class="breadcrumb-item text-white active" aria-current="page">Job List</li>';
echo '</ol>';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '<!-- Header End -->';
echo '';
echo '';
echo '<!-- Jobs Start -->';
echo '<div class="container-xxl py-5">';
echo '<div class="container">';
echo '<h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Job Listing</h1>';
echo '<div class="tab-class text-center wow fadeInUp" data-wow-delay="0.3s">';
echo '<ul class="nav nav-pills d-inline-flex justify-content-center border-bottom mb-5">';
echo '<li class="nav-item">';
echo '<a class="d-flex align-items-center text-start mx-3 ms-0 pb-3 active" data-bs-toggle="pill" href="#tab-1">';
echo '<h6 class="mt-n1 mb-0">Featured</h6>';
echo '</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="d-flex align-items-center text-start mx-3 pb-3" data-bs-toggle="pill" href="#tab-2">';
echo '<h6 class="mt-n1 mb-0">Full Time</h6>';
echo '</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="d-flex align-items-center text-start mx-3 me-0 pb-3" data-bs-toggle="pill" href="#tab-3">';
echo '<h6 class="mt-n1 mb-0">Part Time</h6>';
echo '</a>';
echo '</li>';
echo '</ul>';
echo '<div class="tab-content">';
echo '<div id="tab-1" class="tab-pane fade show p-0 active">';
echo '<div class="job-item p-4 mb-4">';
echo '<div class="row g-4">';
echo '<div class="col-sm-12 col-md-8 d-flex align-items-center">';
echo '<img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-1.jpg" alt="" style="width: 80px; height: 80px;">';
echo '<div class="text-start ps-4">';
echo '<h5 class="mb-3">Software Engineer</h5>';
echo '<span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>';
echo '<span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>';
echo '<span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">';
echo '<div class="d-flex mb-3">';
echo '<a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>';
echo '<a class="btn btn-primary" href="">Apply Now</a>';
echo '</div>';
echo '<small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: 01 Jan, 2045</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="job-item p-4 mb-4">';
echo '<div class="row g-4">';
echo '<div class="col-sm-12 col-md-8 d-flex align-items-center">';
echo '<img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-2.jpg" alt="" style="width: 80px; height: 80px;">';
echo '<div class="text-start ps-4">';
echo '<h5 class="mb-3">Marketing Manager</h5>';
echo '<span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>';
echo '<span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>';
echo '<span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">';
echo '<div class="d-flex mb-3">';
echo '<a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>';
echo '<a class="btn btn-primary" href="">Apply Now</a>';
echo '</div>';
echo '<small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: 01 Jan, 2045</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="job-item p-4 mb-4">';
echo '<div class="row g-4">';
echo '<div class="col-sm-12 col-md-8 d-flex align-items-center">';
echo '<img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-3.jpg" alt="" style="width: 80px; height: 80px;">';
echo '<div class="text-start ps-4">';
echo '<h5 class="mb-3">Product Designer</h5>';
echo '<span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>';
echo '<span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>';
echo '<span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">';
echo '<div class="d-flex mb-3">';
echo '<a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>';
echo '<a class="btn btn-primary" href="">Apply Now</a>';
echo '</div>';
echo '<small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: 01 Jan, 2045</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="job-item p-4 mb-4">';
echo '<div class="row g-4">';
echo '<div class="col-sm-12 col-md-8 d-flex align-items-center">';
echo '<img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-4.jpg" alt="" style="width: 80px; height: 80px;">';
echo '<div class="text-start ps-4">';
echo '<h5 class="mb-3">Creative Director</h5>';
echo '<span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>';
echo '<span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>';
echo '<span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">';
echo '<div class="d-flex mb-3">';
echo '<a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>';
echo '<a class="btn btn-primary" href="">Apply Now</a>';
echo '</div>';
echo '<small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: 01 Jan, 2045</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="job-item p-4 mb-4">';
echo '<div class="row g-4">';
echo '<div class="col-sm-12 col-md-8 d-flex align-items-center">';
echo '<img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-5.jpg" alt="" style="width: 80px; height: 80px;">';
echo '<div class="text-start ps-4">';
echo '<h5 class="mb-3">Wordpress Developer</h5>';
echo '<span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>';
echo '<span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>';
echo '<span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">';
echo '<div class="d-flex mb-3">';
echo '<a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>';
echo '<a class="btn btn-primary" href="">Apply Now</a>';
echo '</div>';
echo '<small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: 01 Jan, 2045</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<a class="btn btn-primary py-3 px-5" href="">Browse More Jobs</a>';
echo '</div>';
echo '<div id="tab-2" class="tab-pane fade show p-0">';
echo '<div class="job-item p-4 mb-4">';
echo '<div class="row g-4">';
echo '<div class="col-sm-12 col-md-8 d-flex align-items-center">';
echo '<img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-1.jpg" alt="" style="width: 80px; height: 80px;">';
echo '<div class="text-start ps-4">';
echo '<h5 class="mb-3">Software Engineer</h5>';
echo '<span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>';
echo '<span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>';
echo '<span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">';
echo '<div class="d-flex mb-3">';
echo '<a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>';
echo '<a class="btn btn-primary" href="">Apply Now</a>';
echo '</div>';
echo '<small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: 01 Jan, 2045</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="job-item p-4 mb-4">';
echo '<div class="row g-4">';
echo '<div class="col-sm-12 col-md-8 d-flex align-items-center">';
echo '<img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-2.jpg" alt="" style="width: 80px; height: 80px;">';
echo '<div class="text-start ps-4">';
echo '<h5 class="mb-3">Marketing Manager</h5>';
echo '<span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>';
echo '<span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>';
echo '<span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">';
echo '<div class="d-flex mb-3">';
echo '<a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>';
echo '<a class="btn btn-primary" href="">Apply Now</a>';
echo '</div>';
echo '<small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: 01 Jan, 2045</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="job-item p-4 mb-4">';
echo '<div class="row g-4">';
echo '<div class="col-sm-12 col-md-8 d-flex align-items-center">';
echo '<img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-3.jpg" alt="" style="width: 80px; height: 80px;">';
echo '<div class="text-start ps-4">';
echo '<h5 class="mb-3">Product Designer</h5>';
echo '<span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>';
echo '<span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>';
echo '<span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">';
echo '<div class="d-flex mb-3">';
echo '<a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>';
echo '<a class="btn btn-primary" href="">Apply Now</a>';
echo '</div>';
echo '<small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: 01 Jan, 2045</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="job-item p-4 mb-4">';
echo '<div class="row g-4">';
echo '<div class="col-sm-12 col-md-8 d-flex align-items-center">';
echo '<img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-4.jpg" alt="" style="width: 80px; height: 80px;">';
echo '<div class="text-start ps-4">';
echo '<h5 class="mb-3">Creative Director</h5>';
echo '<span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>';
echo '<span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>';
echo '<span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">';
echo '<div class="d-flex mb-3">';
echo '<a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>';
echo '<a class="btn btn-primary" href="">Apply Now</a>';
echo '</div>';
echo '<small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: 01 Jan, 2045</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="job-item p-4 mb-4">';
echo '<div class="row g-4">';
echo '<div class="col-sm-12 col-md-8 d-flex align-items-center">';
echo '<img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-5.jpg" alt="" style="width: 80px; height: 80px;">';
echo '<div class="text-start ps-4">';
echo '<h5 class="mb-3">Wordpress Developer</h5>';
echo '<span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>';
echo '<span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>';
echo '<span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">';
echo '<div class="d-flex mb-3">';
echo '<a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>';
echo '<a class="btn btn-primary" href="">Apply Now</a>';
echo '</div>';
echo '<small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: 01 Jan, 2045</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<a class="btn btn-primary py-3 px-5" href="">Browse More Jobs</a>';
echo '</div>';
echo '<div id="tab-3" class="tab-pane fade show p-0">';
echo '<div class="job-item p-4 mb-4">';
echo '<div class="row g-4">';
echo '<div class="col-sm-12 col-md-8 d-flex align-items-center">';
echo '<img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-1.jpg" alt="" style="width: 80px; height: 80px;">';
echo '<div class="text-start ps-4">';
echo '<h5 class="mb-3">Software Engineer</h5>';
echo '<span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>';
echo '<span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>';
echo '<span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">';
echo '<div class="d-flex mb-3">';
echo '<a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>';
echo '<a class="btn btn-primary" href="">Apply Now</a>';
echo '</div>';
echo '<small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: 01 Jan, 2045</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="job-item p-4 mb-4">';
echo '<div class="row g-4">';
echo '<div class="col-sm-12 col-md-8 d-flex align-items-center">';
echo '<img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-2.jpg" alt="" style="width: 80px; height: 80px;">';
echo '<div class="text-start ps-4">';
echo '<h5 class="mb-3">Marketing Manager</h5>';
echo '<span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>';
echo '<span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>';
echo '<span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">';
echo '<div class="d-flex mb-3">';
echo '<a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>';
echo '<a class="btn btn-primary" href="">Apply Now</a>';
echo '</div>';
echo '<small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: 01 Jan, 2045</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="job-item p-4 mb-4">';
echo '<div class="row g-4">';
echo '<div class="col-sm-12 col-md-8 d-flex align-items-center">';
echo '<img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-3.jpg" alt="" style="width: 80px; height: 80px;">';
echo '<div class="text-start ps-4">';
echo '<h5 class="mb-3">Product Designer</h5>';
echo '<span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>';
echo '<span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>';
echo '<span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">';
echo '<div class="d-flex mb-3">';
echo '<a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>';
echo '<a class="btn btn-primary" href="">Apply Now</a>';
echo '</div>';
echo '<small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: 01 Jan, 2045</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="job-item p-4 mb-4">';
echo '<div class="row g-4">';
echo '<div class="col-sm-12 col-md-8 d-flex align-items-center">';
echo '<img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-4.jpg" alt="" style="width: 80px; height: 80px;">';
echo '<div class="text-start ps-4">';
echo '<h5 class="mb-3">Creative Director</h5>';
echo '<span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>';
echo '<span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>';
echo '<span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">';
echo '<div class="d-flex mb-3">';
echo '<a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>';
echo '<a class="btn btn-primary" href="">Apply Now</a>';
echo '</div>';
echo '<small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: 01 Jan, 2045</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="job-item p-4 mb-4">';
echo '<div class="row g-4">';
echo '<div class="col-sm-12 col-md-8 d-flex align-items-center">';
echo '<img class="flex-shrink-0 img-fluid border rounded" src="img/com-logo-5.jpg" alt="" style="width: 80px; height: 80px;">';
echo '<div class="text-start ps-4">';
echo '<h5 class="mb-3">Wordpress Developer</h5>';
echo '<span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>';
echo '<span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>';
echo '<span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">';
echo '<div class="d-flex mb-3">';
echo '<a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>';
echo '<a class="btn btn-primary" href="">Apply Now</a>';
echo '</div>';
echo '<small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: 01 Jan, 2045</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<a class="btn btn-primary py-3 px-5" href="">Browse More Jobs</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Jobs End -->';
echo '';
echo '';
echo '<!-- Footer Start -->';
echo '<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">';
echo '<div class="container py-5">';
echo '<div class="row g-5">';
echo '<div class="col-lg-3 col-md-6">';
echo '<h5 class="text-white mb-4">Company</h5>';
echo '<a class="btn btn-link text-white-50" href="">About Us</a>';
echo '<a class="btn btn-link text-white-50" href="">Contact Us</a>';
echo '<a class="btn btn-link text-white-50" href="">Our Services</a>';
echo '<a class="btn btn-link text-white-50" href="">Privacy Policy</a>';
echo '<a class="btn btn-link text-white-50" href="">Terms & Condition</a>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<h5 class="text-white mb-4">Quick Links</h5>';
echo '<a class="btn btn-link text-white-50" href="">About Us</a>';
echo '<a class="btn btn-link text-white-50" href="">Contact Us</a>';
echo '<a class="btn btn-link text-white-50" href="">Our Services</a>';
echo '<a class="btn btn-link text-white-50" href="">Privacy Policy</a>';
echo '<a class="btn btn-link text-white-50" href="">Terms & Condition</a>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<h5 class="text-white mb-4">Contact</h5>';
echo '<p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>';
echo '<p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>';
echo '<p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>';
echo '<div class="d-flex pt-2">';
echo '<a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>';
echo '<a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>';
echo '<a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>';
echo '<a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<h5 class="text-white mb-4">Newsletter</h5>';
echo '<p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>';
echo '<div class="position-relative mx-auto" style="max-width: 400px;">';
echo '<input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">';
echo '<button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="copyright">';
echo '<div class="row">';
echo '<div class="col-md-6 text-center text-md-start mb-3 mb-md-0">';
echo '&copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.';
echo '';
echo '<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you had like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->';
echo 'Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>';
echo '</div>';
echo '<div class="col-md-6 text-center text-md-end">';
echo '<div class="footer-menu">';
echo '<a href="">Home</a>';
echo '<a href="">Cookies</a>';
echo '<a href="">Help</a>';
echo '<a href="">FQAs</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Footer End -->';
echo '';
echo '';
echo '<!-- Back to Top -->';
echo '<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>';
echo '</div>';
echo '';
echo '<!-- JavaScript Libraries -->';
echo '<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>';
echo '<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>';
echo '<script src="lib/wow/wow.min.js"></script>';
echo '<script src="lib/easing/easing.min.js"></script>';
echo '<script src="lib/waypoints/waypoints.min.js"></script>';
echo '<script src="lib/owlcarousel/owl.carousel.min.js"></script>';
echo '';
echo '<!-- Template Javascript -->';
echo '<script src="js/main.js"></script>';
echo '</body>';
echo '';
echo '</html>';
?>