<?php
echo '<!DOCTYPE html>';
echo '<html lang="en" >';
echo '';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<title>Login</title>';
echo '';
echo '';
echo '<link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Open+Sans:600'>';
echo '';
echo '<link rel="stylesheet" href="./css/login.css">';
echo '';
echo '';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '<div class="login-wrap">';
echo '<div class="login-html">';
echo '<input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Sign In</label>';
echo '<input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Sign Up</label>';
echo '<div class="login-form">';
echo '<form class="sign-in-htm" action="./api/user/login.php" method="GET">';
echo '<div class="group">';
echo '<label for="user" class="label">Username</label>';
echo '<input id="username" name="username" type="text" class="input">';
echo '</div>';
echo '<div class="group">';
echo '<label for="pass" class="label">Password</label>';
echo '<input id="password" name="password" type="password" class="input" data-type="password">';
echo '</div>';
echo '<div class="group">';
echo '<input id="check" type="checkbox" class="check" >';
echo '<label for="check"><span class="icon"></span> Keep me Signed in</label>';
echo '</div>';
echo '<div class="group">';
echo '<input type="submit" class="button" value="Sign In">';
echo '</div>';
echo '<div class="hr"></div>';
echo '<div class="foot-lnk">';
echo '<a href="#forgot">Forgot Password?</a>';
echo '</div>';
echo '</form>';
echo '<form class="sign-up-htm" action="./api/user/signup.php" method="POST">';
echo '<div class="group">';
echo '<label for="user" class="label">Username</label>';
echo '<input id="username" name="username" type="text" class="input">';
echo '</div>';
echo '<div class="group">';
echo '<label for="pass" class="label">Password</label>';
echo '<input id="password" name="password" type="password" class="input" data-type="password">';
echo '</div>';
echo '<div class="group">';
echo '<label for="pass" class="label">Confirm Password</label>';
echo '<input id="pass" type="password" class="input" data-type="password">';
echo '</div>';
echo '<div class="group">';
echo '<input type="submit" class="button" value="Sign Up">';
echo '</div>';
echo '<div class="hr"></div>';
echo '<div class="foot-lnk">';
echo '<label for="tab-1">Already Member?</a>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '';
echo '</body>';
echo '';
echo '</html>';
?>